version: "3.9"
services:

  postgres-db:
    image: postgres:15.3-alpine
    env_file:
      - .env
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-db-data:/var/lib/postgresql/data/

  fast-todo:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./:/code/
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres-db-data: